swagger: "2.0"
info:
  version: 1.0.0
  title: "Pilotos"
  description: Semplice API che permette di inserire, modificare e eliminare Pilotos.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: pilotosapp.herokuapp.com
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pilotos:
    get:
      description: |
        Ritorna tutti gli pilotos.
      operationId: findPilotos
      responses:
        200:
          description: piloto response
          schema:
            type: array
            items:
              $ref: '#/definitions/Piloto'
    post:
      description: |
        Crea un piloto.
      operationId: addPiloto
      parameters:
        - name: piloto
          in: body
          required: true
          schema:
            $ref: '#/definitions/Piloto'
      responses:
        200:
          description: piloto response
          schema:
            $ref: '#/definitions/Piloto'
            
  /pilotos/{id}:
    get:
      description: |
        Ritorna l'piloto con l'pilotoId specificato.
      operationId: findPilotoById
      parameters:
        - name: id
          in: path
          required: true
          type: string
          x-example: '46'
      responses:
        200:
          description: piloto response
          schema:
            $ref: '#/definitions/Piloto'
    delete:
      description: |
        Elimina l'piloto con l'pilotoId specificato.
      operationId: deletePiloto
      parameters:
        - name: id
          in: path
          required: true
          type: string
          x-example: '46'
      responses:
        204:
          description: piloto deleted
    put:
      description: |
        Modifica l'piloto con l'pilotoId specificato.
      operationId: updatePilotoById
      parameters:
        - name: id
          in: path
          required: true
          type: string
          x-example: '46'
        - name: piloto
          in: body
          required: true
          schema:
            $ref: '#/definitions/Piloto'
      responses:
        200:
          description: piloto response
          schema:
            $ref: '#/definitions/Piloto'
definitions:
  Piloto:
    required:
      - pilotoId
      - name
      - surname
      - bike
    properties:
      pilotoId:
        type: string
      name:
        type: string
      surname:
        type: string
      bike:
        type: string